/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account5 {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "balances")]
    pub balances: crate::models::Balances5,
    #[serde(rename = "days_available")]
    pub days_available: i32,
    #[serde(rename = "historical_balances")]
    pub historical_balances: Vec<crate::models::HistoricalBalance>,
    #[serde(rename = "mask")]
    pub mask: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "official_name")]
    pub official_name: Option<String>,
    #[serde(rename = "owners")]
    pub owners: Vec<crate::models::Owner>,
    #[serde(rename = "subtype")]
    pub subtype: String,
    #[serde(rename = "transactions")]
    pub transactions: Vec<crate::models::Transaction1>,
    #[serde(rename = "type")]
    pub _type: String,
}

impl Account5 {
    pub fn new(account_id: String, balances: crate::models::Balances5, days_available: i32, historical_balances: Vec<crate::models::HistoricalBalance>, mask: String, name: String, official_name: Option<String>, owners: Vec<crate::models::Owner>, subtype: String, transactions: Vec<crate::models::Transaction1>, _type: String) -> Account5 {
        Account5 {
            account_id,
            balances,
            days_available,
            historical_balances,
            mask,
            name,
            official_name,
            owners,
            subtype,
            transactions,
            _type,
        }
    }
}


