/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Balances5 {
    #[serde(rename = "available")]
    pub available: i32,
    #[serde(rename = "current")]
    pub current: i32,
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: String,
    #[serde(rename = "unofficial_currency_code")]
    pub unofficial_currency_code: Option<String>,
}

impl Balances5 {
    pub fn new(available: i32, current: i32, iso_currency_code: String, unofficial_currency_code: Option<String>) -> Balances5 {
        Balances5 {
            available,
            current,
            iso_currency_code,
            unofficial_currency_code,
        }
    }
}


