/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Credit {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "aprs")]
    pub aprs: Vec<crate::models::Apr>,
    #[serde(rename = "is_overdue")]
    pub is_overdue: bool,
    #[serde(rename = "last_payment_amount")]
    pub last_payment_amount: f32,
    #[serde(rename = "last_payment_date")]
    pub last_payment_date: String,
    #[serde(rename = "last_statement_balance")]
    pub last_statement_balance: f32,
    #[serde(rename = "last_statement_issue_date")]
    pub last_statement_issue_date: String,
    #[serde(rename = "minimum_payment_amount")]
    pub minimum_payment_amount: i32,
    #[serde(rename = "next_payment_due_date")]
    pub next_payment_due_date: String,
}

impl Credit {
    pub fn new(account_id: String, aprs: Vec<crate::models::Apr>, is_overdue: bool, last_payment_amount: f32, last_payment_date: String, last_statement_balance: f32, last_statement_issue_date: String, minimum_payment_amount: i32, next_payment_due_date: String) -> Credit {
        Credit {
            account_id,
            aprs,
            is_overdue,
            last_payment_amount,
            last_payment_date,
            last_statement_balance,
            last_statement_issue_date,
            minimum_payment_amount,
            next_payment_due_date,
        }
    }
}


