/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPaymentResponse {
    #[serde(rename = "payment_id")]
    pub payment_id: String,
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "amount")]
    pub amount: crate::models::PaymentAmount,
    #[serde(rename = "status")]
    pub status: crate::models::PaymentStatus,
    #[serde(rename = "recipient_id")]
    pub recipient_id: String,
    #[serde(rename = "reference")]
    pub reference: String,
    #[serde(rename = "last_status_update")]
    pub last_status_update: String,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<serde_json::Value>,
}

impl GetPaymentResponse {
    pub fn new(payment_id: String, request_id: String, amount: crate::models::PaymentAmount, status: crate::models::PaymentStatus, recipient_id: String, reference: String, last_status_update: String) -> GetPaymentResponse {
        GetPaymentResponse {
            payment_id,
            request_id,
            amount,
            status,
            recipient_id,
            reference,
            last_status_update,
            schedule: None,
        }
    }
}


