/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebhookVerificationKeyResponseKey {
    #[serde(rename = "alg")]
    pub alg: String,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<f32>,
    #[serde(rename = "expired_at", skip_serializing_if = "Option::is_none")]
    pub expired_at: Option<f32>,
    #[serde(rename = "crv")]
    pub crv: String,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "kty")]
    pub kty: String,
    #[serde(rename = "use")]
    pub _use: String,
    #[serde(rename = "x")]
    pub x: String,
    #[serde(rename = "y")]
    pub y: String,
}

impl GetWebhookVerificationKeyResponseKey {
    pub fn new(alg: String, crv: String, kid: String, kty: String, _use: String, x: String, y: String) -> GetWebhookVerificationKeyResponseKey {
        GetWebhookVerificationKeyResponseKey {
            alg,
            created_at: None,
            expired_at: None,
            crv,
            kid,
            kty,
            _use,
            x,
            y,
        }
    }
}


