/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeStream {
    #[serde(rename = "confidence")]
    pub confidence: f32,
    #[serde(rename = "days")]
    pub days: i32,
    #[serde(rename = "monthly_income")]
    pub monthly_income: i32,
    #[serde(rename = "name")]
    pub name: String,
}

impl IncomeStream {
    pub fn new(confidence: f32, days: i32, monthly_income: i32, name: String) -> IncomeStream {
        IncomeStream {
            confidence,
            days,
            monthly_income,
            name,
        }
    }
}


