/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Item {
    #[serde(rename = "available_products")]
    pub available_products: Vec<String>,
    #[serde(rename = "billed_products")]
    pub billed_products: Vec<String>,
    #[serde(rename = "error")]
    pub error: Option<String>,
    #[serde(rename = "institution_id")]
    pub institution_id: String,
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "webhook")]
    pub webhook: String,
}

impl Item {
    pub fn new(available_products: Vec<String>, billed_products: Vec<String>, error: Option<String>, institution_id: String, item_id: String, webhook: String) -> Item {
        Item {
            available_products,
            billed_products,
            error,
            institution_id,
            item_id,
            webhook,
        }
    }
}


