/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mortgage {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "account_number")]
    pub account_number: String,
    #[serde(rename = "current_late_fee")]
    pub current_late_fee: i32,
    #[serde(rename = "escrow_balance")]
    pub escrow_balance: f32,
    #[serde(rename = "has_pmi")]
    pub has_pmi: bool,
    #[serde(rename = "has_prepayment_penalty")]
    pub has_prepayment_penalty: bool,
    #[serde(rename = "interest_rate")]
    pub interest_rate: crate::models::InterestRate,
    #[serde(rename = "last_payment_amount")]
    pub last_payment_amount: f32,
    #[serde(rename = "last_payment_date")]
    pub last_payment_date: String,
    #[serde(rename = "loan_term")]
    pub loan_term: String,
    #[serde(rename = "loan_type_description")]
    pub loan_type_description: String,
    #[serde(rename = "maturity_date")]
    pub maturity_date: String,
    #[serde(rename = "next_monthly_payment")]
    pub next_monthly_payment: f32,
    #[serde(rename = "next_payment_due_date")]
    pub next_payment_due_date: String,
    #[serde(rename = "origination_date")]
    pub origination_date: String,
    #[serde(rename = "origination_principal_amount")]
    pub origination_principal_amount: i32,
    #[serde(rename = "past_due_amount")]
    pub past_due_amount: i32,
    #[serde(rename = "property_address")]
    pub property_address: crate::models::PropertyAddress,
    #[serde(rename = "ytd_interest_paid")]
    pub ytd_interest_paid: f32,
    #[serde(rename = "ytd_principal_paid")]
    pub ytd_principal_paid: f32,
}

impl Mortgage {
    pub fn new(account_id: String, account_number: String, current_late_fee: i32, escrow_balance: f32, has_pmi: bool, has_prepayment_penalty: bool, interest_rate: crate::models::InterestRate, last_payment_amount: f32, last_payment_date: String, loan_term: String, loan_type_description: String, maturity_date: String, next_monthly_payment: f32, next_payment_due_date: String, origination_date: String, origination_principal_amount: i32, past_due_amount: i32, property_address: crate::models::PropertyAddress, ytd_interest_paid: f32, ytd_principal_paid: f32) -> Mortgage {
        Mortgage {
            account_id,
            account_number,
            current_late_fee,
            escrow_balance,
            has_pmi,
            has_prepayment_penalty,
            interest_rate,
            last_payment_amount,
            last_payment_date,
            loan_term,
            loan_type_description,
            maturity_date,
            next_monthly_payment,
            next_payment_due_date,
            origination_date,
            origination_principal_amount,
            past_due_amount,
            property_address,
            ytd_interest_paid,
            ytd_principal_paid,
        }
    }
}


