/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Options1 {
    #[serde(rename = "webhook")]
    pub webhook: String,
    #[serde(rename = "override_username")]
    pub override_username: String,
    #[serde(rename = "override_password")]
    pub override_password: String,
}

impl Options1 {
    pub fn new(webhook: String, override_username: String, override_password: String) -> Options1 {
        Options1 {
            webhook,
            override_username,
            override_password,
        }
    }
}


