/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Owner {
    #[serde(rename = "addresses")]
    pub addresses: Vec<crate::models::Address1>,
    #[serde(rename = "emails")]
    pub emails: Vec<crate::models::Email>,
    #[serde(rename = "names")]
    pub names: Vec<String>,
    #[serde(rename = "phone_numbers")]
    pub phone_numbers: Vec<crate::models::PhoneNumber>,
}

impl Owner {
    pub fn new(addresses: Vec<crate::models::Address1>, emails: Vec<crate::models::Email>, names: Vec<String>, phone_numbers: Vec<crate::models::PhoneNumber>) -> Owner {
        Owner {
            addresses,
            emails,
            names,
            phone_numbers,
        }
    }
}


