/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentStatus {
    #[serde(rename = "PAYMENT_STATUS_INPUT_NEEDED")]
    INPUTNEEDED,
    #[serde(rename = "PAYMENT_STATUS_PROCESSING")]
    PROCESSING,
    #[serde(rename = "PAYMENT_STATUS_INITIATED")]
    INITIATED,
    #[serde(rename = "PAYMENT_STATUS_COMPLETED")]
    COMPLETED,
    #[serde(rename = "PAYMENT_STATUS_INSUFFICIENT_FUNDS")]
    INSUFFICIENTFUNDS,
    #[serde(rename = "PAYMENT_STATUS_FAILED")]
    FAILED,
    #[serde(rename = "PAYMENT_STATUS_BLOCKED")]
    BLOCKED,
    #[serde(rename = "PAYMENT_STATUS_UNKNOWN")]
    UNKNOWN,

}




