/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMeta {
    #[serde(rename = "by_order_of")]
    pub by_order_of: Option<String>,
    #[serde(rename = "payee")]
    pub payee: Option<String>,
    #[serde(rename = "payer")]
    pub payer: Option<String>,
    #[serde(rename = "payment_method")]
    pub payment_method: Option<String>,
    #[serde(rename = "payment_processor")]
    pub payment_processor: Option<String>,
    #[serde(rename = "ppd_id")]
    pub ppd_id: Option<String>,
    #[serde(rename = "reason")]
    pub reason: Option<String>,
    #[serde(rename = "reference_number")]
    pub reference_number: Option<String>,
}

impl PaymentMeta {
    pub fn new(by_order_of: Option<String>, payee: Option<String>, payer: Option<String>, payment_method: Option<String>, payment_processor: Option<String>, ppd_id: Option<String>, reason: Option<String>, reference_number: Option<String>) -> PaymentMeta {
        PaymentMeta {
            by_order_of,
            payee,
            payer,
            payment_method,
            payment_processor,
            ppd_id,
            reason,
            reference_number,
        }
    }
}


