/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    #[serde(rename = "asset_report_id")]
    pub asset_report_id: String,
    #[serde(rename = "client_report_id")]
    pub client_report_id: Option<String>,
    #[serde(rename = "date_generated")]
    pub date_generated: String,
    #[serde(rename = "days_requested")]
    pub days_requested: i32,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::Item7>,
    #[serde(rename = "user")]
    pub user: crate::models::User5,
}

impl Report {
    pub fn new(asset_report_id: String, client_report_id: Option<String>, date_generated: String, days_requested: i32, items: Vec<crate::models::Item7>, user: crate::models::User5) -> Report {
        Report {
            asset_report_id,
            client_report_id,
            date_generated,
            days_requested,
            items,
            user,
        }
    }
}


