/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveInvestmentsHoldingsResponse {
    #[serde(rename = "accounts")]
    pub accounts: crate::models::RetrieveAnItemsAccountsResponse,
    #[serde(rename = "holdings")]
    pub holdings: serde_json::Value,
    #[serde(rename = "securities")]
    pub securities: serde_json::Value,
    #[serde(rename = "item")]
    pub item: crate::models::RetrieveItemResponse,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl RetrieveInvestmentsHoldingsResponse {
    pub fn new(accounts: crate::models::RetrieveAnItemsAccountsResponse, holdings: serde_json::Value, securities: serde_json::Value, item: crate::models::RetrieveItemResponse, request_id: String) -> RetrieveInvestmentsHoldingsResponse {
        RetrieveInvestmentsHoldingsResponse {
            accounts,
            holdings,
            securities,
            item,
            request_id,
        }
    }
}


