/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveInsitutionListRequest {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "country_codes")]
    pub country_codes: Vec<String>,
}

impl RetrieveInsitutionListRequest {
    pub fn new(client_id: String, secret: String, count: i32, offset: i32, country_codes: Vec<String>) -> RetrieveInsitutionListRequest {
        RetrieveInsitutionListRequest {
            client_id,
            secret,
            count,
            offset,
            country_codes,
        }
    }
}


