/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveLiabilitiesReportExample {
    #[serde(rename = "report")]
    pub report: crate::models::Report1,
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "warnings")]
    pub warnings: Option<String>,
}

impl RetrieveLiabilitiesReportExample {
    pub fn new(report: crate::models::Report1, request_id: String, warnings: Option<String>) -> RetrieveLiabilitiesReportExample {
        RetrieveLiabilitiesReportExample {
            report,
            request_id,
            warnings,
        }
    }
}


