/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction1 {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "account_owner")]
    pub account_owner: Option<String>,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "category")]
    pub category: Option<Vec<String>>,
    #[serde(rename = "category_id")]
    pub category_id: Option<String>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "date_transacted")]
    pub date_transacted: Option<String>,
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: String,
    #[serde(rename = "location")]
    pub location: crate::models::Location,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "original_description")]
    pub original_description: String,
    #[serde(rename = "payment_meta")]
    pub payment_meta: crate::models::PaymentMeta,
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "pending_transaction_id")]
    pub pending_transaction_id: Option<String>,
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "transaction_type")]
    pub transaction_type: String,
    #[serde(rename = "unofficial_currency_code")]
    pub unofficial_currency_code: Option<String>,
}

impl Transaction1 {
    pub fn new(account_id: String, account_owner: Option<String>, amount: i32, category: Option<Vec<String>>, category_id: Option<String>, date: String, date_transacted: Option<String>, iso_currency_code: String, location: crate::models::Location, name: String, original_description: String, payment_meta: crate::models::PaymentMeta, pending: bool, pending_transaction_id: Option<String>, transaction_id: String, transaction_type: String, unofficial_currency_code: Option<String>) -> Transaction1 {
        Transaction1 {
            account_id,
            account_owner,
            amount,
            category,
            category_id,
            date,
            date_transacted,
            iso_currency_code,
            location,
            name,
            original_description,
            payment_meta,
            pending,
            pending_transaction_id,
            transaction_id,
            transaction_type,
            unofficial_currency_code,
        }
    }
}


