/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction2 {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "iso_currency_code")]
    pub iso_currency_code: String,
    #[serde(rename = "original_description")]
    pub original_description: String,
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "unofficial_currency_code")]
    pub unofficial_currency_code: Option<String>,
}

impl Transaction2 {
    pub fn new(account_id: String, amount: i32, date: String, iso_currency_code: String, original_description: String, pending: bool, transaction_id: String, unofficial_currency_code: Option<String>) -> Transaction2 {
        Transaction2 {
            account_id,
            amount,
            date,
            iso_currency_code,
            original_description,
            pending,
            transaction_id,
            unofficial_currency_code,
        }
    }
}


