/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User4 {
    #[serde(rename = "client_user_id")]
    pub client_user_id: String,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "middle_name")]
    pub middle_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "ssn")]
    pub ssn: String,
    #[serde(rename = "phone_number")]
    pub phone_number: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl User4 {
    pub fn new(client_user_id: String, first_name: String, middle_name: String, last_name: String, ssn: String, phone_number: String, email: String) -> User4 {
        User4 {
            client_user_id,
            first_name,
            middle_name,
            last_name,
            ssn,
            phone_number,
            email,
        }
    }
}


