/*
 * Plaid API Endpoints Copy 2
 *
 * A collection of Plaid API endpoints for the `sandbox` environment. Each endpoint request comes with an example request & response. It also contains 'use cases' for each product.   <br /> Before you begin, please set your `client_id` and `secret_key` variables in the Sandbox environment. You can find them in your Plaid [dashboard](https://dashboard.plaid.com/account/keys). Set the variables by clicking on the 'eye' icon in the top-right corner of the screen.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User5 {
    #[serde(rename = "client_user_id")]
    pub client_user_id: Option<String>,
    #[serde(rename = "email")]
    pub email: Option<String>,
    #[serde(rename = "first_name")]
    pub first_name: Option<String>,
    #[serde(rename = "last_name")]
    pub last_name: Option<String>,
    #[serde(rename = "middle_name")]
    pub middle_name: Option<String>,
    #[serde(rename = "phone_number")]
    pub phone_number: Option<String>,
    #[serde(rename = "ssn")]
    pub ssn: Option<String>,
}

impl User5 {
    pub fn new(client_user_id: Option<String>, email: Option<String>, first_name: Option<String>, last_name: Option<String>, middle_name: Option<String>, phone_number: Option<String>, ssn: Option<String>) -> User5 {
        User5 {
            client_user_id,
            email,
            first_name,
            last_name,
            middle_name,
            phone_number,
            ssn,
        }
    }
}


